### ISSUE TITLE
Responsive design for Code Blocks

### ISSUE THREAD

**Issue by schoenenberg** [schoenenberg/zola-paper#1]
Code blocks on small screens look horrible.. Need to fix that!

**Comment by schoenenberg** [comment]
It seems this is related mostly to Firefox. I have to check this..

**Comment by ghost** [comment]
Hey @schoenenberg. Thanks for the theme!

I modified the `css` to add `overflow-x: auto;`, which will keep the code within the bounds of the code block and allows the visiter to scroll for longer code lines. I'll test this on a smaller screen when I publish my site. In the meanwhile, here are side-by-side comparisons with and without the overflow.

<img width="302" alt="Screenshot 2022-10-31 at 9 28 41 PM" src="https://user-images.githubusercontent.com/114830266/199138944-63869eb5-dce9-48bf-b402-cc29ed1c1977.png"><img width="302" alt="Screenshot 2022-10-31 at 9 28 53 PM" src="https://user-images.githubusercontent.com/114830266/199138952-000c1326-1cb4-49f6-b0b6-62b93c433d09.png">

Left: existing CSS, Right: with `overflow-x: auto;` (I've 'scrolled' the code a bit, but just showing that it doesn't add width to the entire page)

**Comment by ghost** [comment]
I made another modification that improves how code blocks display on smaller screens. I essentially removed these two lines: https://github.com/schoenenberg/zola-paper/blob/master/sass/_theme.scss#L400-L401

<img width="300" alt="Screenshot 2022-11-01 at 9 34 09 PM" src="https://user-images.githubusercontent.com/114830266/199374101-dbc9d8ef-4e64-4efa-b9d5-1a8636f4d33b.png">

I'd be more than happy to open a PR with these changes if you're interested!

**Comment by schoenenberg** [comment]
Hi @Borlaag,

thanks for the effort to fix the theme! I will be happy to review and merge the PR :)
