### ISSUE TITLE
Articles require `<!-- more -->` otherwise page will crash

### ISSUE THREAD

**Issue by peterkos** [schoenenberg/zola-paper#5]
## Description

Following up on https://github.com/getzola/zola/issues/1298, the theme appears to use a redundant call to `| markdown(inline = true)`, which causes a crash when `page.summary` is null, i.e., when `<!-- more --> ` is not defined. This makes summaries required, and imo, they shouldn't be! :) 

Relevant area of code:
https://github.com/schoenenberg/zola-paper/blob/643041d20be22e2f32a31ac8759e0431d93f28db/templates/index.html#L17

## Reproduction steps
1. Remove `<!-- more -->` from any article in `content/`
2. Attempt to compile
3. Observe this error:
```shell
Reason: Failed to render 'page.html' (error happened in 'index.html').
Reason: Filter call 'markdown' failed
Reason: Filter `markdown` was called on an incorrect value: got `null` but expected a String
```

**Comment by schoenenberg** [comment]
Thanks for reporting it!

**Comment by schoenenberg** [comment]
Thanks for reporting this issue! I like the fi
